CREATE SCHEMA `BankDetails`;

CREATE  TABLE `BankDetails`.`ACCOUNT` (
    ACCOUNT_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
    ACCOUNT_REF VARCHAR(50) NOT NULL,
    AMOUNT DECIMAL(19,2) NOT NULL,
    CURRENCY CHAR(3) NOT NULL,
    PRIMARY KEY (ACCOUNT_ID),
    UNIQUE KEY `UNIQUE_ACCOUNT_REF` (`ACCOUNT_REF`)
);

CREATE TABLE `BankDetails`.`TRANSACTION`(
     TRANS_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
     TRANS_REF varchar(50) NOT NULL,
     TRANS_TYPE varchar(25) NOT NULL,
     TRANS_DATE  timestamp NOT NULL,
     PRIMARY KEY(TRANS_ID),
     UNIQUE KEY `UNIQUE_TRANS_REF`(`TRANS_REF`)
);


CREATE TABLE `BankDetails`.`TRANSACTION_LEG`(
      LEG_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
      TRANS_REF varchar(50) NOT NULL,
      ACCOUNT_REF varchar(50) NOT NULL,
      AMOUNT DECIMAL(19,2) NOT NULL,
      CURRENCY CHAR(3) NOT NULL,
      PRIMARY KEY(LEG_ID),
      KEY `FK_TRANS_REF` (`TRANS_REF`),
      CONSTRAINT `FK_TRANS_REF` FOREIGN KEY (`TRANS_REF`) REFERENCES `transaction` (`TRANS_REF`)

);
